# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela de cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 337)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nome_cadastro = QtWidgets.QLineEdit(self.centralwidget)
        self.nome_cadastro.setGeometry(QtCore.QRect(60, 90, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.nome_cadastro.setFont(font)
        self.nome_cadastro.setText("")
        self.nome_cadastro.setObjectName("nome_cadastro")
        self.senha_cadastro = QtWidgets.QLineEdit(self.centralwidget)
        self.senha_cadastro.setGeometry(QtCore.QRect(60, 210, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.senha_cadastro.setFont(font)
        self.senha_cadastro.setText("")
        self.senha_cadastro.setObjectName("senha_cadastro")
        self.confirmar_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.confirmar_senha.setGeometry(QtCore.QRect(60, 250, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.confirmar_senha.setFont(font)
        self.confirmar_senha.setText("")
        self.confirmar_senha.setObjectName("confirmar_senha")
        self.cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.cadastrar.setGeometry(QtCore.QRect(320, 280, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.cadastrar.setFont(font)
        self.cadastrar.setObjectName("cadastrar")
        self.email_cadastro = QtWidgets.QLineEdit(self.centralwidget)
        self.email_cadastro.setGeometry(QtCore.QRect(60, 140, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.email_cadastro.setFont(font)
        self.email_cadastro.setText("")
        self.email_cadastro.setObjectName("email_cadastro")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 120, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 190, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 230, 111, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.cadastrar.clicked.connect(self.fazer_cadastro)

            #    FUNCIONA

    # def fazer_cadastro(self):
    #     name = str(self.nome_cadastro.text())
    #     email = str(self.email_cadastro.text())
    #
    #     password = str(self.senha_cadastro.text())
    #     conf_password = str(self.confirmar_senha.text())
    #
    #     print(name, email)
    #     print(password, conf_password)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CADASTRO"))
        self.cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label_2.setText(_translate("MainWindow", "Senha deve conter caracteres especias"))
        self.label_3.setText(_translate("MainWindow", "Nome completo"))
        self.label_4.setText(_translate("MainWindow", "E-mail"))
        self.label_5.setText(_translate("MainWindow", "Digite a senha"))
        self.label_6.setText(_translate("MainWindow", "Confirme a senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
