# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela de login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 337)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.logar = QtWidgets.QPushButton(self.centralwidget)
        self.logar.setGeometry(QtCore.QRect(60, 200, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.logar.setFont(font)
        self.logar.setObjectName("logar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.email_login = QtWidgets.QLineEdit(self.centralwidget)
        self.email_login.setGeometry(QtCore.QRect(60, 100, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.email_login.setFont(font)
        self.email_login.setText("")
        self.email_login.setObjectName("email_login")
        self.senha_login = QtWidgets.QLineEdit(self.centralwidget)
        self.senha_login.setGeometry(QtCore.QRect(60, 160, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.senha_login.setFont(font)
        self.senha_login.setText("")
        self.senha_login.setObjectName("senha_login")
        self.criar_conta = QtWidgets.QPushButton(self.centralwidget)
        self.criar_conta.setGeometry(QtCore.QRect(310, 280, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.criar_conta.setFont(font)
        self.criar_conta.setObjectName("criar_conta")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 280, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

                # FUNCIONA

    #     self.logar.clicked.connect(self.login_conta)
    #
    #
    # def login_conta(self):
    #     user = str(self.email_login.text())
    #     password = str(self.senha_login.text())
    #
    #     print(user,password)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LOGIN"))
        self.logar.setText(_translate("MainWindow", "Logar"))
        self.label_2.setText(_translate("MainWindow", "Seu e-mail"))
        self.label_3.setText(_translate("MainWindow", "Sua senha"))
        self.criar_conta.setText(_translate("MainWindow", "cria conta"))
        self.label_4.setText(_translate("MainWindow", "Ainda não tem conta?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

